[[Algencan]]
arch = "x86_64"
git-tree-sha1 = "4a2b12926dd1dcccee294a8e7b630947a2c18061"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "8753e75a5fadbcc53d718f1675d7f047c3887f68ff255aa1d935cda0b3a093d9"
    url = "https://github.com/amontoison/Algencan_jll.jl/releases/download/Algencan-v3.1.1+0/Algencan.v3.1.1.x86_64-linux-gnu-libgfortran5.tar.gz"
