# Autogenerated wrapper script for Algencan_jll for x86_64-linux-gnu-libgfortran5
export libalgencan

using CompilerSupportLibraries_jll
using libblastrampoline_jll
JLLWrappers.@generate_wrapper_header("Algencan")
JLLWrappers.@declare_library_product(libalgencan, "libalgencan.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, libblastrampoline_jll)
    JLLWrappers.@init_library_product(
        libalgencan,
        "lib/libalgencan.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
